version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run: sudo pip install pytest
      - run: sudo pip install mypy
      - run: sudo pip install flake8
      - run: flake8
      - run: mypy -p pork
      - run: python -m pytest -v
