version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run: sudo pip install pytest
      - run: sudo pip install mypy
      - run: sudo pip install flake8
      - run: python -m flake8
      - run: python -m mypy -p pork --ignore-missing-imports
      - run: python -m pytest -v
